# Introduction to NumPy

Adapted by [Nimblebox Inc.](https://www.nimblebox.ai/) from the `Data-X: Introduction to Numpy` tutorial by [Alexander Fred Ojala](https://alex.fo/) and [Ikhlaq Sidhu](https://vcresearch.berkeley.edu/faculty/ikhlaq-sidhu),  [`Python Data Science Handbook`](http://shop.oreilly.com/product/0636920034919.do) by [Jake VanderPlas](https://github.com/jakevdp/PythonDataScienceHandbook) and [`NumPy Documentation`](https://numpy.org/doc/1.17/index.html).

## Introduction:  

NumPy stands for **Numerical Python** and it is the fundamental package for scientific computing in Python. It is a package that lets you efficiently store and manipulate numerical arrays. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities


In this tutorial, we will cover:

* **Basics**: Different ways to create NumPy Arrays and Basics of NumPy
* **Computation**: Computations on NumPy arrays using Universal Functions and other NumPy Routines
* **Aggregations**: Various function used to aggregate for NumPy arrays

### NumPy contains an array object that is "fast"


<img src="https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/threefundamental.png">


**It stores / consists of**:
* location of a memory block (allocated all at one time)
* a shape (3 x 3 or 1 x 9, etc)
* data type / size of each element

The core feauture that NumPy supports is its multi-dimensional arrays. In NumPy, dimensions are called axes and the number of axes is called a rank.

### NumPy Array Anotomy
<img src= "https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/anatomyarray.png">


We'll start with the standard NumPy import, under the alias `np`

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.17.4


### Basics of NumPy Array

#### 1. Creating a NumPy Array

##### From Python List

We use `np.array` to create a numpy array object from python list.

In [3]:
# Create array from Python list
list1 = [1, 2, 3, 4]
data = np.array(list1)
print(data)

[1 2 3 4]


In [4]:
# Find out object type
print(type(list1))
print(type(data))

<class 'list'>
<class 'numpy.ndarray'>


Python being a dynamically typed language, Python lists can contain elements with hetarogenous data-types. But NumPy is constrained to array with which have homogenous data-types. If the data types are not homogenous, NumPy will upcast (if possible) to the most logical data type

In [5]:
# NumPy converts to most logical data type
data1 = np.array([1.2, 2, 3, 4])
print(data1)
print(data1.dtype) # all values will be converted to floats

[1.2 2.  3.  4. ]
float64


In [6]:
# Here if we store a float in an int array, the float will be up-casted to an int
list2 = [1, 2, 3, 4]
data2 = np.array(list2)
data2[0] = 3.14159
print(data2)

[3 2 3 4]


In [7]:
# We can manually specify the datatype
data3 = np.array([1, 2, 3], dtype="str")
print(data3)
print(data3.dtype)

['1' '2' '3']
<U1


In order to perform any mathematical operations on NumPy arrays, all the elements must be of a type that is valid to perform these mathematical operations.

In [8]:
#This will give you a TypeError
'''
a = np.random.normal(0,1,1000)
b = np.arange(1000, dtype=np.int8)
c = np.arange(1000, dtype=np.int16)
c += a + b
print(c)
'''

'\na = np.random.normal(0,1,1000)\nb = np.arange(1000, dtype=np.int8)\nc = np.arange(1000, dtype=np.int16)\nc += a + b\nprint(c)\n'

In [9]:
# error is resolved by just changing the dtype of 'a' manually
a = np.random.normal(0,1,10)
a = a.astype(np.int16)
b = np.arange(10, dtype=np.int16)
c = np.arange(10, dtype=np.int16)
c += a + b
print(c)

[ 0  2  4  4  8 10 12 14 16 19]


Unlike python list, we can create multi-dimensional arrays using NumPy.

In [10]:
# nested lists result in multi-dimensional arrays
x1 = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(x1)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


For more information and other NumPy operations based on Python list, refer to the [NumPy documentation](http://numpy.org/).

##### Using NumPy routines

When dealing with very large array, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [11]:
# Create a length-10 integer array filled with zeros
print(np.zeros(10, dtype=int))

[0 0 0 0 0 0 0 0 0 0]


In [12]:
# Create a 3x5 floating-point array filled with ones
print(np.ones((3, 5), dtype=float))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# Create a 3x5 array filled with 3.14
print(np.full((3, 5), 3.14))

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [14]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
print(np.arange(0, 20, 2))

[ 0  2  4  6  8 10 12 14 16 18]


In [15]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
print(np.random.random((3, 3)))

[[0.63871786 0.2470147  0.17758035]
 [0.78127032 0.88110625 0.50778067]
 [0.33712322 0.0077388  0.87694999]]


In [16]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
print(np.random.normal(0, 1, (3, 3)))

[[ 0.5123426  -0.55012137 -0.2685287 ]
 [-1.34533849 -0.06752169 -1.14771069]
 [ 0.38368952  0.31460891 -1.44230895]]


In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)
print(np.random.randint(0, 10, (3, 3)))

[[0 7 1]
 [7 1 6]
 [8 3 0]]


In [18]:
# Returns the identity matrix of specific squared size
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


You can always explore the [documentation](http://numpy.org/) for more.

#### 2. Basics of NumPy Array

##### Attributes of NumPy Array

Each NumPy array has the following attributes,

In [19]:
x3 = np.random.randint(10, size=(3, 4, 5))  # Create a 3-D array

print("x3 ndim: ", x3.ndim) # np.ndim yields the number of dimensions 
print("x3 shape:", x3.shape) # np.shape yields the size of each dimension
print("x3 size: ", x3.size) # np.size yields the total size of the array
print("dtype:", x3.dtype) # np.dtype yields the data type of the array
print("itemsize:", x3.itemsize, "bytes") # np.itemsize yields the size (in bytes) of each array element
print("nbytes:", x3.nbytes, "bytes") # np.nbytes yields the total size (in bytes) of the array

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


For more information, refer the [documentation](http://numpy.org/).

##### Accessing elements: Slicing and Indexing

Slicing and Indexing of NumPy Arrays is quite similar to that of Python lists

In [102]:
data = np.arange(10) # Create a 1-D array
print("Original Data:\n", data, "\n")

# Indexing
print("Indexing NumPy Array:")
print("  ", data[4]) # 4th element of the numpy array
print("  ", data[-1], "\n") # 1st element from right side of the numpy array

# Slicing: To access a slice of an array 'data', we use this `data[start:stop:step]`
print("Slicing NumPy Array:")
print("  ", data[:5]) # First 5 element of the numpy array
print("  ", data[::-1]) # All the elements of the numpy array but in reverse order


Original Data:
 [0 1 2 3 4 5 6 7 8 9] 

Indexing NumPy Array:
   4
   9 

Slicing NumPy Array:
   [0 1 2 3 4]
   [9 8 7 6 5 4 3 2 1 0]


<u><i>Indexing in a multi-dimentional NumPy Array</i></u>: Multi-dimensional indices work in the same way, with multiple indices separated by commas

In [21]:
# Let's create a 3-D array
x3 = np.random.randint(10, size=(3, 4, 5))
print(x3)

[[[2 2 1 1 2]
  [0 8 9 9 0]
  [6 8 1 7 4]
  [6 4 6 5 7]]

 [[0 3 7 8 8]
  [2 1 9 2 8]
  [3 0 5 0 1]
  [9 9 5 3 1]]

 [[5 3 3 9 4]
  [5 8 4 6 3]
  [7 8 2 1 9]
  [0 6 7 5 8]]]


In [22]:
print(x3[1]) # prints the 2nd 4x5 array in the generated 3-D array

[[0 3 7 8 8]
 [2 1 9 2 8]
 [3 0 5 0 1]
 [9 9 5 3 1]]


In [23]:
print(x3[1,2]) # prints the 3rd row of the x3[1] array

[3 0 5 0 1]


In [24]:
print(x3[1,2,3]) # prints the 4th element of the x3[1,2] array

0


<u><i>Slicing in a multi-dimentional NumPy Array</i></u>: Multi-dimensional slices work in the same way, with multiple slices separated by commas

In [25]:
# Let's create a 3-D array
x3 = np.random.randint(10, size=(3, 4, 5))
print(x3)

[[[4 5 7 7 8]
  [2 9 3 8 9]
  [5 7 0 1 0]
  [8 2 0 2 8]]

 [[4 5 6 6 5]
  [3 5 0 4 0]
  [8 6 6 5 3]
  [1 4 1 9 7]]

 [[2 1 7 8 1]
  [0 9 2 6 8]
  [8 0 4 7 1]
  [9 4 1 0 5]]]


In [87]:
print(x3[:2, :3, :4])  # prints a 3x4x5 array is sliced into 2x3x4 array

[[[4 5 7 7]
  [2 9 3 8]
  [5 7 0 1]]

 [[4 5 6 6]
  [3 5 0 4]
  [8 6 6 5]]]


<u><i>Mask Indexing and Boolean Slicing</i></u>: These technique are used to filter and get quick inference about the nature of the dataset that we have

In [91]:
# Mask Indexing
numpy_array = np.random.randint(1, 11, size=(10))
print("NumPy Array:\n", numpy_array, "\n")

# Let's create a mask for the 'numpy_array' such that we can filter out the elements that are 'greater than 5'
mask = numpy_array > 5
print("Masked Array:\n", mask, "\n")

# Now let's just print the elements that follow our condition
print("Interested Array:\n", numpy_array[mask])

NumPy Array:
 [6 7 3 1 2 8 7 5 5 5] 

Masked Array:
 [ True  True False False False  True  True False False False] 

Interested Array:
 [6 7 8 7]


For further exploration, refer the [documentation](https://numpy.org/doc/1.17/user/basics.indexing.html) of NumPy

##### Python Lists and NumPy Arrays

NumPy utilizes efficient pointers to a location in memory and it will store the full array. Lists on the other hand are pointers to many different objects in memory.

<u><i>Subarray (default returns)</i></u>: Slicing returns a view for a NumPy Array, where as Python Lists returns a copy the list

In [27]:
# Let's create a NumPy Array and slice it
data_numpy = np.random.randint(10, size=(10))
print("Pre-slicing NumPy Array: ", data_numpy)
slicing_numpy = data_numpy[0:3]
print("Slice of NumPy Array: ", slicing_numpy)

# Let's create a Python List and slice it
import random
data_list = random.sample(range(0, 10), 10)
print("\nPre-slicing Python List: ", data_list)
slicing_list = data_list[0:3]
print("Slice of Python List: ", slicing_list)

Pre-slicing NumPy Array:  [5 5 8 5 6 4 0 7 0 2]
Slice of NumPy Array:  [5 5 8]

Pre-slicing Python List:  [2, 8, 5, 3, 9, 0, 6, 7, 1, 4]
Slice of Python List:  [2, 8, 5]


In [28]:
# Let's change the first element of both array and list
slicing_numpy[0] = -1
print("Slice of NumPy Array: ", slicing_numpy)
slicing_list[0] = -1
print("Slice of Python List: ", slicing_list)

Slice of NumPy Array:  [-1  5  8]
Slice of Python List:  [-1, 8, 5]


In [29]:
print("Post-slicing NumPy array: ", data_numpy) # has changed
print("Post-slicing Python list: ", data_list) # has not changed

Post-slicing NumPy array:  [-1  5  8  5  6  4  0  7  0  2]
Post-slicing Python list:  [2, 8, 5, 3, 9, 0, 6, 7, 1, 4]


<u><i>Subarray (custom)</i></u>: Slicing of NumPy Array should create a copy of the array just like Python Lists

In [30]:
# Creating copies of the array instead of views
data_numpy = np.random.randint(10, size=(10))
print("Pre-slicing NumPy Array: ", data_numpy)
slicing_numpy_copy = data_numpy[0:3].copy()
print("Slice of NumPy Array: ", slicing_numpy_copy)

Pre-slicing NumPy Array:  [7 8 4 8 0 7 4 0 0 6]
Slice of NumPy Array:  [7 8 4]


In [31]:
# Let's chage the first element of our numpy array and observe
slicing_numpy_copy[0] = -1
print("Post-slicing NumPy Array: ", slicing_numpy_copy)
print("Pre-slicing NumPy Array: ", data_numpy) # now it is not a view any more but we created a copy of data_numpy

Post-slicing NumPy Array:  [-1  8  4]
Pre-slicing NumPy Array:  [7 8 4 8 0 7 4 0 0 6]


Question - Making train and test sets: Create two arrays from `original_data`, one with 2/3 and the other with 1/3 of the elements. 

Note that you don't want to mess up your original data set when you (later) make transformations on the train / test set.

In [32]:
original_data = np.arange(1000)
np.random.shuffle(original_data) # inplace

#input answer

### Computation 

#### 1. Universal Function
A universal function (or ufunc) that is applied on an `ndarray` in an element-by-element fashion. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.

In [33]:
# Let's define two NumPy Arrays
x = np.random.randint(1, 11, size=(10))
y = np.random.randint(1, 11, size=(10))
print ("Array 'x' = ", x)
print ("Array 'y' = ", y)

Array 'x' =  [ 1 10  9 10 10  3  6  8  6  5]
Array 'y' =  [5 1 1 2 9 8 2 9 7 7]


In [34]:
# Let's perform some arithmetic on these arrays
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)  # floor division
print(x % y)

[ 6 11 10 12 19 11  8 17 13 12]
[-4  9  8  8  1 -5  4 -1 -1 -2]
[ 5 10  9 20 90 24 12 72 42 35]
[ 0.2        10.          9.          5.          1.11111111  0.375
  3.          0.88888889  0.85714286  0.71428571]
[ 0 10  9  5  1  0  3  0  0  0]
[1 0 0 0 1 3 0 8 6 5]


Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy, for example, the `+` operator is a wrapper for the `add` function

In [35]:
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.mod(x, y))

[ 6 11 10 12 19 11  8 17 13 12]
[-4  9  8  8  1 -5  4 -1 -1 -2]
[ 5 10  9 20 90 24 12 72 42 35]
[1 0 0 0 1 3 0 8 6 5]


The following table lists some of the `ufunc` implemented in NumPy:


| Universal Functions	  | Operator (if any)  | Description                                                    |
|:-----------------------:|:------------------:|:--------------------------------------------------------------:|
|``np.add``               | ``+``              |Addition (e.g., ``[10  6  8] + [3 10  6] = [13 16 14]``)        |
|``np.subtract``          | ``-``              |Subtraction (e.g., ``[10  6  8] - [3 10  6] = [ 7 -4  2]``)     |
|``np.negative``          | ``-``              |Unary negation (e.g., ``[-10  -6  -8]``)                        |
|``np.multiply``          | ``*``              |Multiplication (e.g., ``[10  6  8] * [3 10  6] = [30 60 48]``)  |
|``np.divide``            | ``/``              |Division (e.g., ``[10  6  8] / [3 10  6] = [3.33 0.6 1.33]``)   |
|``np.floor_divide``      | ``//``             |Floor division (e.g., ``[10  6  8] // [3 10  6] = [3 0 1]``)    |
|``np.mod``               | ``%``              |Modulus/remainder (e.g., ``[10  6  8] % [3 10  6] = [1 6 2]``)  |
|``np.log``               |                    |Natural logarithm, element-wise                                 |
|``np.log2``              |                    |Base-2 logarithm of x                                           |


More information on universal functions (including the full list of available functions) can found in the NumPy [documentation](https://numpy.org/doc/1.17/reference/ufuncs.html).

Question: Ax = b. Solve for x. Note, you should use numpy's pseudoinverse function while aligning A and b's dimensions. 

In [36]:
A = np.array([[1, 2, 3, 4, 5, 6]]).reshape(3,2)
b = np.array([7,8,9]).reshape(3,-1)
print(A, "\n")
print(b)

# input answer
# print(x)

[[1 2]
 [3 4]
 [5 6]] 

[[7]
 [8]
 [9]]


#### 2. NumPy Routines

NumPy being a the scientific computing package, it has several in-build routines/functions to aid mathematical and scientific computing. Some of the common routines used in Machine Learning are discussed below.

In [86]:
# NumPy allows use to concatenate or append different NumPy Arrays
a = np.random.randint(1, 11, size=(3, 3, 2))
b = np.random.randint(1, 11, size=(3, 3, 3))
c = np.ones((1, 3, 2), dtype="int32")
d = np.ones((3, 1, 2), dtype="int32")

print("'a':\n", a, "\n")
print("'b':\n", b, "\n")
print("'c':\n", c, "\n")
print("'d':\n", d, "\n")

# Let's concatenate 'a' and 'b' together alond axis=2
print("Concatenate:\n", np.concatenate((a, b), axis=2), "\n")

# Let's append 'c' to 'a' vertically
print("Vertical Append:\n", np.vstack((a, c)), "\n") # try appending 'd' to 'a' vertically

# Let's append 'd' to 'a' horizontally
print("Horizontal Append:\n", np.hstack((a, d))) # try appending 'c' to 'a' horizontally

'a':
 [[[ 7  7]
  [ 6 10]
  [ 4  9]]

 [[ 7  1]
  [10  2]
  [ 8  7]]

 [[ 9 10]
  [ 9  6]
  [ 4  7]]] 

'b':
 [[[ 9  8  9]
  [ 2  9 10]
  [ 9  9  7]]

 [[ 7  4  3]
  [ 8  9  1]
  [ 8  4 10]]

 [[ 7  8  4]
  [ 3  6  1]
  [ 7 10  3]]] 

'c':
 [[[1 1]
  [1 1]
  [1 1]]] 

'd':
 [[[1 1]]

 [[1 1]]

 [[1 1]]] 

Concatenate:
 [[[ 7  7  9  8  9]
  [ 6 10  2  9 10]
  [ 4  9  9  9  7]]

 [[ 7  1  7  4  3]
  [10  2  8  9  1]
  [ 8  7  8  4 10]]

 [[ 9 10  7  8  4]
  [ 9  6  3  6  1]
  [ 4  7  7 10  3]]] 

Vertical Append:
 [[[ 7  7]
  [ 6 10]
  [ 4  9]]

 [[ 7  1]
  [10  2]
  [ 8  7]]

 [[ 9 10]
  [ 9  6]
  [ 4  7]]

 [[ 1  1]
  [ 1  1]
  [ 1  1]]] 

Horizontal Append:
 [[[ 7  7]
  [ 6 10]
  [ 4  9]
  [ 1  1]]

 [[ 7  1]
  [10  2]
  [ 8  7]
  [ 1  1]]

 [[ 9 10]
  [ 9  6]
  [ 4  7]
  [ 1  1]]]


In [94]:
# Let's create a random NumPy Array
numpy_array = np.random.randint(1, 11, size=(9))
print("Original Array Shape: ", numpy_array.shape)
print("Original Array: ", numpy_array, "\n")

# Using np.reshape() routine to reshape an array
numpy_array = numpy_array.reshape(3,3)
print("New Array Shape: ", numpy_array.shape)
print("New Array:\n", numpy_array)

Original Array Shape:  (9,)
Original Array:  [7 7 3 2 8 6 1 8 6] 

New Array Shape:  (3, 3)
New Array:
 [[7 7 3]
 [2 8 6]
 [1 8 6]]


In [39]:
# We can also flatten matrices using ravel()
numpy_array = np.random.randint(1, 11, size=(24))
numpy_array = numpy_array.reshape(4,6)
print("Original Array Shape: ", numpy_array.shape)
print("Original Array:\n", numpy_array, "\n")

# Flattening an unflattened array
numpy_array = numpy_array.ravel()
print("Flattened Array Shape: ", numpy_array.shape)
print ("Flattened Array:\n", numpy_array)

Original Array Shape:  (4, 6)
Original Array:
 [[ 9  4  6  6  7  4]
 [ 9  7  1 10  4  4]
 [ 2  9  9  6 10  7]
 [ 5  7  2 10  7  8]] 

Flattened Array Shape:  (24,)
Flattened Array:
 [ 9  4  6  6  7  4  9  7  1 10  4  4  2  9  9  6 10  7  5  7  2 10  7  8]


In [97]:
# Other useful routines for data analysis using NumPy
numpy_array = np.random.randint(1, 11, size=(3, 4))

print(numpy_array, "\n")
print ("Sum of all Elements:", numpy_array.sum())
print("Smallest Element:", numpy_array.min())
print("Highest Element:", numpy_array.max())
print("Cumulative Sum of Elements:", numpy_array.cumsum())
print ("Column-wise Sum:", numpy_array.sum(axis=0))
print ("Row-wise Sum:",numpy_array.sum(axis=1))

[[ 6  8  4 10]
 [ 9  4  7  4]
 [ 6  3  7  7]] 

Sum of all Elements: 75
Smallest Element: 3
Highest Element: 10
Cumulative Sum of Elements: [ 6 14 18 28 37 41 48 52 58 61 68 75]
Column-wise Sum: [21 15 18 21]
Row-wise Sum: [28 24 23]


You can do matrix multiplication and matrix manipulations

In [60]:
# Dot products of two "arrays"
a = np.random.randint(1, 11, size=(3, 3))
b = np.random.randint(1, 11, size=(3, 3))

print("'a':\n", a, "\n")
print("'b':\n", b, "\n")

print("Dot Product of 'a' and 'b' (arrays):\n", np.dot(a, b))

'a':
 [[4 1 7]
 [5 8 9]
 [9 9 9]] 

'b':
 [[10  5  5]
 [ 2  9  9]
 [ 3 10  2]] 

Dot Product of 'a' and 'b':
 [[ 63  99  43]
 [ 93 187 115]
 [135 216 144]]


In [68]:
# Matrix product of two "arrays"
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(4, 2))

print("'a':\n", a, "\n")
print("'b':\n", b, "\n")

print("Matrix Product of 'a' and 'b' (arrays):\n", np.matmul(a, b))

'a':
 [[7 3 2 3]
 [4 3 2 2]
 [1 7 5 3]] 

'b':
 [[ 6  4]
 [ 7  7]
 [10  9]
 [ 7  3]] 

Matrix Product of 'a' and 'b' (arrays):
 [[104  76]
 [ 79  61]
 [126 107]]


In [72]:
# Taking the transpose of an array Matrix
a = np.random.randint(1, 11, size=(3, 4))
print("'a':\n", a, "\n")

# You can take transpose in two ways
print("'a' Transpose (using 'array.T'):\n", a.T, "\n")
print("'a' Transpose (using 'np.transpose()''):\n", np.transpose(a), "\n")

'a':
 [[ 8  1  9 10]
 [10 10  2  4]
 [ 5  6  2  3]] 

'a' Transpose (using 'array.T'):
 [[ 8 10  5]
 [ 1 10  6]
 [ 9  2  2]
 [10  4  3]] 

'a' Transpose (using 'np.transpose()''):
 [[ 8 10  5]
 [ 1 10  6]
 [ 9  2  2]
 [10  4  3]] 



There so many more routines available in this package. To explore all the NumPy routines, refer the [documentation](https://numpy.org/doc/1.17/reference/routines.html).